// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetUmbracoDragonflythemingApiV1CssOverridesData, GetUmbracoDragonflythemingApiV1CssOverridesErrors, GetUmbracoDragonflythemingApiV1CssOverridesResponses, GetUmbracoDragonflythemingApiV1PingData, GetUmbracoDragonflythemingApiV1PingErrors, GetUmbracoDragonflythemingApiV1PingResponses, GetUmbracoDragonflythemingApiV1ThemesData, GetUmbracoDragonflythemingApiV1ThemesErrors, GetUmbracoDragonflythemingApiV1ThemesResponses, GetUmbracoDragonflythemingApiV1WhatsMyNameData, GetUmbracoDragonflythemingApiV1WhatsMyNameErrors, GetUmbracoDragonflythemingApiV1WhatsMyNameResponses, GetUmbracoDragonflythemingApiV1WhatsTheTimeMrWolfData, GetUmbracoDragonflythemingApiV1WhatsTheTimeMrWolfErrors, GetUmbracoDragonflythemingApiV1WhatsTheTimeMrWolfResponses, GetUmbracoDragonflythemingApiV1WhoAmIData, GetUmbracoDragonflythemingApiV1WhoAmIErrors, GetUmbracoDragonflythemingApiV1WhoAmIResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class DragonflyUmbracoThemingService {
    public static getUmbracoDragonflythemingApiV1CssOverrides<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoDragonflythemingApiV1CssOverridesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoDragonflythemingApiV1CssOverridesResponses, GetUmbracoDragonflythemingApiV1CssOverridesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/dragonflytheming/api/v1/css-overrides',
            ...options
        });
    }
    
    public static getUmbracoDragonflythemingApiV1Ping<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoDragonflythemingApiV1PingData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoDragonflythemingApiV1PingResponses, GetUmbracoDragonflythemingApiV1PingErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/dragonflytheming/api/v1/ping',
            ...options
        });
    }
    
    public static getUmbracoDragonflythemingApiV1Themes<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoDragonflythemingApiV1ThemesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoDragonflythemingApiV1ThemesResponses, GetUmbracoDragonflythemingApiV1ThemesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/dragonflytheming/api/v1/themes',
            ...options
        });
    }
    
    public static getUmbracoDragonflythemingApiV1WhatsMyName<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoDragonflythemingApiV1WhatsMyNameData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoDragonflythemingApiV1WhatsMyNameResponses, GetUmbracoDragonflythemingApiV1WhatsMyNameErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/dragonflytheming/api/v1/whatsMyName',
            ...options
        });
    }
    
    public static getUmbracoDragonflythemingApiV1WhatsTheTimeMrWolf<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoDragonflythemingApiV1WhatsTheTimeMrWolfData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoDragonflythemingApiV1WhatsTheTimeMrWolfResponses, GetUmbracoDragonflythemingApiV1WhatsTheTimeMrWolfErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/dragonflytheming/api/v1/whatsTheTimeMrWolf',
            ...options
        });
    }
    
    public static getUmbracoDragonflythemingApiV1WhoAmI<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoDragonflythemingApiV1WhoAmIData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoDragonflythemingApiV1WhoAmIResponses, GetUmbracoDragonflythemingApiV1WhoAmIErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/dragonflytheming/api/v1/whoAmI',
            ...options
        });
    }
}
